### ISSUE TITLE
Load schedule from QR code without internet

### ISSUE THREAD

**Issue by eladeyal-intel** [Wilm0r/giggity#105]
I would like the ability to transfer the whole schedule to the smartphone using QR code only. It can be useful for places where the agenda is not available over the internet (enterprise environment).

For example you can take [frab scehdule.xml](https://programm.froscon.de/2018/schedule.xml) , `gzip -9 | qr` , create a qr code, and then be able to scan this directly into Giggity. Example QR code:

![image](https://user-images.githubusercontent.com/20379005/57233817-0cf69480-7028-11e9-89ec-9dbc34cf532e.png)

If I understand [this code](https://github.com/Wilm0r/giggity/blob/503c286ec66a3b449092dd9575859e638d1e9b8f/app/src/main/java/net/gaast/giggity/ChooserActivity.java#L269) correctly, the barcode reader can't do that, but it is seems easy to add.

**Comment by Wilm0r** [comment]
Huh wait, how much data is that one gunzipped? Only very tiny schedules 
would fit in a QR code that size I think?

Even with the JSON fragment gzip+qr trick documented in the README, 
elaborate files (with lots of links and/or room location info) could end 
up in QRs that my phone could barely still scan.

**Comment by eladeyal-intel** [comment]
I agree that for large conferences such as FOSDEM2019 it becomes too large for QR generationg.

But I want to make the claim that it's useful for some of the conferences. I picked randomally some conferences from [the builtin ones](https://github.com/Wilm0r/giggity/tree/a7b4e18eda8e30eaceea7075d4271e922ed36656/menu) and they all fit in a QR code. It can be scanned from a printout or from screen and be useful for some scenarios.

GUADEC2018

![image](https://user-images.githubusercontent.com/20379005/57281493-c189c800-70b3-11e9-95f9-179cc5b010fe.png)

capitole_du_libre_2018

![image](https://user-images.githubusercontent.com/20379005/57282187-34477300-70b5-11e9-8da3-c95fb425502d.png)

JDLL 2019

![image](https://user-images.githubusercontent.com/20379005/57282340-85effd80-70b5-11e9-94a4-1ed31a5443a1.png)

35c3 main rooms only
![image](https://user-images.githubusercontent.com/20379005/57282639-26462200-70b6-11e9-9126-d080766a92bd.png)

thanks

**Comment by eladeyal-intel** [comment]
@Wilm0r ?

**Comment by eladeyal-intel** [comment]
@Wilm0r  you can do it! :-)

**Comment by Wilm0r** [comment]
Thanks for pinging! Sorry I'm traveling and not able to pay much attention for a while :-(

Anyway, your GUADEC2018 example decodes to 800 bytes of compressed data, I still struggle to understand how that one can contain useful enough data.. how much is that after decompression? Is that with all descriptions strpiped, leaving just 1 day of data and a few times + talk titles for a small number of rooms? The original file at https://2018.guadec.org/documents/schedule.xml is 50KB, gzip -9 takes that to a whopping 13KB..

**Comment by eladeyal-intel** [comment]
@Wilm0r  good catch... `qr.exe` from `python-qr` encoder was encoding an incomplete file.
