### ISSUE TITLE
Improve UI to display more data and implement material design

### ISSUE THREAD

**Issue by heysadboy** [Wilm0r/giggity#12]
- We could add padding between the texts and present it in points and we could move the things from toolbar to the text views under it in points.
- Display the data in CardViews to make one group more separable than other.
- Expand the columns on click to make the text more visible.

Corresponding activities to be improved.

<table>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26516303/ac99e656-42a1-11e7-814b-607c6a702cc1.png">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26516304/ae2967c6-42a1-11e7-90d8-917b66002257.png">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26516305/b1d51a14-42a1-11e7-93c5-d1ddd690178c.png">
</td>
</table>

@Wilm0r I use this [link](https://raw.githubusercontent.com/heysadboy/Giggity-Parser/master/Parser/sample.xml) to add our FOSSASIA data in your app. We have other data too like images and we look up to add that support to in Giggity app, please review this. 

It would be great if you could also add FOSSASIA 2016 in your app, I mailed you the data, if not through pull request for further testing of UI on our data. Is there any changes required to be made except in menu.json for our conference to be reflected in app, I wonder.

**Comment by Wilm0r** [comment]
Sorry for the slowness, I am on a trip in a far-ish timezone, but noticed the conf is in August so that's why I haven't rushed this yet.

I'll get it merged hopefully within the next few days!

**Comment by heysadboy** [comment]
@Wilm0r It is okay, I was looking this up to test further. Enjoy your trip :-)
