### ISSUE TITLE
Giggity fails to update schedule, raises java.lang.SecurityException 

### ISSUE THREAD

**Issue by hmpf** [Wilm0r/giggity#147]
I'm working out what to attempt to see at FOSDEM. For multitrack cons, giggity has been my favorite tool for years. Block schedule with hiding FTW!

But: Giggity started failing today with 

> java.lang.SecurityException: !@Too many alarms (500)

I found an old discussion at stackoverflow: [java.lang.SecurityException: !@Too many alarms (500) registered from pid 10790 uid 10206](https://stackoverflow.com/questions/29344971/java-lang-securityexception-too-many-alarms-500-registered-from-pid-10790-u). If this has the same cause, this only happens on Samsung phones, which is what I have :/  .

Especially annoying:

>  "We've found that devices where this problem occurs will be in a broken state (filled with PendingIntents?) until they are restarted or the app is reinstalled."

I have tested on my own Samsung: restarting the entire device is no longer a working workaround, I'm a bit reluctant to reinstall since I assume this will erase all the selections I've already made.

**Comment by Wilm0r** [comment]
Hah, as it happens I've discovered just this weekend how bad and stale the alarm/notification code had become. Can you still start the app and temporarily disable the reminders at least? I'm not at the right time for doing a new release yet.

**Comment by Wilm0r** [comment]
(Though I'm still curious what caused the alarms because 500 is an insane number and shouldn't be happening. The code was bad but not *that* bad. How much did you have selected?)

**Comment by hmpf** [comment]
Looks like 28 reminders on Sunday, lots of overlap.

But ***yes***, turning off notifications (for anyone else with this problem, gear wheel on the page where you select conferences) fixes the problem, without messing with the actual selections.

From the stackoverflow issue it seems the problem is a leak, so I guess those 28 get multiplied whenever the schedule is refetched. Doesn't take long to get over 500 then (28, 56, 112, 224, 448, BANG).

**Comment by Wilm0r** [comment]
Yes I can see that happening pretty quickly if deduplication is broken
:-( And I wonder whether that's indeed a Samsung bug then, because it's
not meant to happen, AFAIK alarms are deduped by their unique id's, and
Giggity does reuse the same ID for each reminder.

Currently it uses Java's hashCode() built-in for that but I've just
rewritten it this weekend to do an md5 on the schedule URL + item ID so
maybe there was a "Java bug" that I've coincidentally fixed now.

Can I send you a semi-release .apk tonight so you can see whether it
fixes the issue?

(Also I can just add a try-except for SEcurity Exceptions around the
alarms code to be on the safe side.)

Also, if you're willing to share the output of

adb shell dumpsys alarm

with me, possibly I can verify then what's happening (are the intents
the same but the silence IDs somehow randomised?).

**Comment by kaleissin** [comment]
(APK) I'm at UTC+1 at the moment, and this evening I'm busy. I can test tomorrow (daytime) though.

(ADB) I've never needed adb for this phone before so I'd have to set things up. Where *have* Samsung hidden things away this time around...

**Comment by kaleissin** [comment]
Bloody Konami code... "press this magic place seven times for developer mode!!!".

The resulting dump is nearly 500K. Anything in particular you need? "Pending alarm batches" is 582, for a total of 751 alarms. There are excatly 500 occurences of **tag=*walarm*:net.gaast.giggity.ALARM**, seems to be one batch per. Do you want those?

**Comment by Wilm0r** [comment]
Oh cool you're quick, thank you for figuring out the Konami :-D (I think
it's 7× tapping on plain Android as well, normally on the build
version/ID somewhere behind 3 levels of settings menu?)

If you can figure out a few seemingly duplicate alarms (belonging to the
same event ID behind the # in the URL?) that'd be cool. (Or just all 500
if pastebin allows?)

If not, I did do some reading yesterday and it looks like Samsung just
has "fascinating" ways of deduplicating this, plus in general alarms +
pending intents have a only barely comprehensible reuse/recycle policy
anyway.

In the commit above I've made some changes that should A) avoid these
problems and B) not crash but issue a "Toast" warning if a
SecurityException does still occur.

On top of this I should also only set alarms that are <1d away really.
OTOH thanks to the code *not* having that check, you were able to report
this bug now instead of right during FOSDEM, for which I'm also pretty
grateful. (-:


`//

**Comment by Wilm0r** [comment]
(Oh yes, I'll post a link here tonight to a release-signed .apk with that fix
included.)

**Comment by Wilm0r** [comment]
https://gaa.st/~wilmer/.giggity.apk

**Comment by kaleissin** [comment]
There's 18 copies of an alarm with `when=2020-02-01 10:25:00.000`, here's two of them:

```
Batch{4905e85 num=1 start=3713846735 end=3713846735 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{2bb1d87 type 0 when 1580549100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+24d19h39m53s504ms expectedMaxWhenElapsed=+24d19h39m53s504ms whenElapsed=+24d19h39m53s503ms maxWhenElapsed=+24d19h39m53s503ms when=2020-02-01 10:25:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{289bb82: PendingIntentRecord{1eae1e0 net.gaast.giggity broadcastIntent}}
Batch{e22f4da num=1 start=3713846735 end=3713846735 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{df133a1 type 0 when 1580549100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+24d19h39m53s503ms expectedMaxWhenElapsed=+24d19h39m53s503ms whenElapsed=+24d19h39m53s503ms maxWhenElapsed=+24d19h39m53s503ms when=2020-02-01 10:25:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{9969a15: PendingIntentRecord{bfb8e22 net.gaast.giggity broadcastIntent}}
```

The only thing that is similar is the times, anything that looks like an id is unique. Worse, I have no selections made for Saturday yet, so, *wat*? Maybe I made a selection, unmade it, and it wasn't removed?

Sunday has 11 entries for something with `when=2020-02-02 08:55:00.000`, I'll paste in all of those:

```
Batch{18e203d num=1 start=3794846735 end=3794846735 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{88d3f8b type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s503ms expectedMaxWhenElapsed=+25d18h9m53s503ms whenElapsed=+25d18h9m53s503ms maxWhenElapsed=+25d18h9m53s503ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{4c6a1e7: PendingIntentRecord{321280d net.gaast.giggity broadcastIntent}}
Batch{3848032 num=1 start=3794846735 end=3794846735 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{48c5d05 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s503ms maxWhenElapsed=+25d18h9m53s503ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{38813da: PendingIntentRecord{6705897 net.gaast.giggity broadcastIntent}}
Batch{7260183 num=1 start=3794846735 end=3794846735 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{36c5b6f type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s503ms expectedMaxWhenElapsed=+25d18h9m53s503ms whenElapsed=+25d18h9m53s503ms maxWhenElapsed=+25d18h9m53s503ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{ef229c9: PendingIntentRecord{7ce6ea4 net.gaast.giggity broadcastIntent}}
Batch{df6bf00 num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{5379175 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{58423ef: PendingIntentRecord{ee24123 net.gaast.giggity broadcastIntent}}
Batch{a418339 num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{b31217b type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{6915ee8: PendingIntentRecord{41ab524 net.gaast.giggity broadcastIntent}}
Batch{af66d7e num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{1ac1503 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{6404901: PendingIntentRecord{79fc2c2 net.gaast.giggity broadcastIntent}}
Batch{dbd32df num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{9fa82b9 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{fea9985: PendingIntentRecord{6d36986 net.gaast.giggity broadcastIntent}}
Batch{688cb2c num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{950fe5f type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{4d38ce: PendingIntentRecord{63aeb2b net.gaast.giggity broadcastIntent}}
Batch{62e19f5 num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{8e27bd type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{6104efc: PendingIntentRecord{c9ea102 net.gaast.giggity broadcastIntent}}
Batch{607e38a num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{18e4967 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s504ms expectedMaxWhenElapsed=+25d18h9m53s504ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{76393a6: PendingIntentRecord{8636edf net.gaast.giggity broadcastIntent}}
Batch{f6c1dfb num=1 start=3794846736 end=3794846736 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{9fac481 type 0 when 1580630100000 net.gaast.giggity}
      tag=*walarm*:net.gaast.giggity.ALARM
      type=0 expectedWhenElapsed=+25d18h9m53s503ms expectedMaxWhenElapsed=+25d18h9m53s503ms whenElapsed=+25d18h9m53s504ms maxWhenElapsed=+25d18h9m53s504ms when=2020-02-02 08:55:00.000
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{b99100b: PendingIntentRecord{e21923d net.gaast.giggity broadcastIntent}}
```

I have two selections for things starting 09:00 that day so that at least makes sense.

**Comment by kaleissin** [comment]
APK tested, no exception raised. Still lots of garbage when dumping the alarms though.

**Comment by Wilm0r** [comment]
Cool, thanks! Feel free to reopen if you do run into this again.
