### ISSUE TITLE
which event type are supported

### ISSUE THREAD

**Issue by lucadelu** [Wilm0r/giggity#149]
Hi,

I create a pentabarf xml response to show the calendar of our conference (you can see it [here](https://foss4g-it2020.gfoss.it/pentabarf), but I'm not able to see in giggity the event elements which `type` different from talk (we have poster and workshop).

Is it possible to use different values for `type` ?

**Comment by Wilm0r** [comment]
Hrm, interesting, hadn't run into that kind of distinction before. What are you using it for? I don't think Giggity is even reading it so I wonder why this is causing things to not show up.

**Comment by Wilm0r** [comment]
"Analisi dati per l'individuazione delle High Natural Value areas in Piemonte" is showing up okay for me. One thing I do notice is:

```xml
<event id="10034">
<date>2020-01-27T13:30:00</date>
<start>13:30:00</start>
```
Note the <date/> field with date + time that is actually today not the 20th of Feb.

Maybe there are/were more bugs like that in your generator?

**Comment by lucadelu** [comment]
> 
> Maybe there are/were more bugs like that in your generator?

Yes, there was two more bug one related to workshop (duplicated id) and two for poster (
duplicated id and wrong datetime) 

now it works well. sorry for the noise
