### ISSUE TITLE
Respect Timezones in XMLs

### ISSUE THREAD

**Issue by joker234** [Wilm0r/giggity#162]
With [SotM 2020](https://2020.sotm.org) ([XML](https://sotm.osmz.ru/2020.xml)) using giggity I recognized, that reminders and program is not in local timezone but UTC. It would be nice if the local timezone (of the android device) would be used, but not that annoying. It's more annoying that I (currently in UTC+2) get the reminders two hours early. It would be nice if giggity could handle timezones properly.

The XML looks correct:
```xml
…
  <day index="1" date="2020-07-04" start="2020-07-04T10:00:00Z" end="2020-07-04T22:32:00Z">
    <room name="Track 1">
      <event guid="66470e9c-d19d-5670-9918-0248be67c02d" id="5028">
        <date>2020-07-04T10:00:00Z</date>
        <start>10:00</start>
        <duration>00:20</duration>
        <room>Track 1</room>
        <slug>sotm2020-5028-opening</slug>
        <url>https://pretalx.com/sotm2020/talk/AXAUHX/</url>
        <recording>
          <license></license>
          <optout>false</optout>
        </recording>
        <title>Opening</title>
        <subtitle></subtitle>
        <track>OSM Basics</track>
        <type>Talk</type>
        <language>en</language>
        <abstract>Welcome to SotM 2020!</abstract>
        <description>Welcome to SotM 2020!

Some words about how the virtual SotM will run.</description>
        <logo></logo>
        <persons>
          <person id="2297">SotM Working Group</person>
        </persons>
        <links/>
        <attachments/>
      </event>
…
```

**Comment by Wilm0r** [comment]
Agreed, I figured a few weeks ago that I'm going to have to add this to Giggity. When I wrote the parser, IIRC Pentabarf files didn't have useful tz info yet (also Java tz APIs were terrible, fortunately I've adopted a more modern one kinda recently which is going to be useful here).

When I considered implementing this earlier, I couldn't really figure out what to do UI-wise. But I guess it should just read all times with tz info and offer a choice between showing conf-local or user-local times (when they differ at all).

**Comment by Wilm0r** [comment]
This came up in https://github.com/Wilm0r/giggity/pull/164 too, and I've managed to fix it in time before that event :-)

Behaviour is not configurable and will work only with Pentabarf files with those timestamps. Note that this is not in all Pentabarf style files for example not in FOSDEM's schedule: https://fosdem.org/2020/schedule/xml — it has only <start/> blocks with naive times, not the <date/> full-ISO8601 ones. But files that do, like HOPE and many others (in fact FOSDEM is the only exception I found so far) will now be parsed with timezone offset.

Then when tz offset is different from the phone's configured tz, the times will be converted, and the nav drawer will mention the offset as an FYI.

Alerts should all work properly now. Maybe later I'll add a setting to *show* event-local times. I *think* everything else it timezone-clean enough that this should work properly. (One could possibly try by just changing `tzNative` in `Schedule.java`.

**Comment by Wilm0r** [comment]
2.0.6 released on Play and hopefully soon F-Droid (depends on when their bot scans the repository)

Since some confs like FOSDEM don't have this info, and since hour offsets are less useful than *actual* timezone info, I wonder whether I'll just add a tz field to `menu.json` for more complete support later.

**Comment by Wilm0r** [comment]
> Since some confs like FOSDEM don't have this info, and since hour offsets are less useful than actual timezone info, I wonder whether I'll just add a tz field to menu.json for more complete support later.

IIRC I saw that Debconf *does* have a timezone header in its files somewhere which sounds useful. Guess support for that is worth keeping this bug open for.

**Comment by Wilm0r** [comment]
a079f481 did this already.
