### ISSUE TITLE
DateTimeParserException for simple dates (e.g. Bibliothekartag 2020)

### ISSUE THREAD

**Issue by zuphilip** [Wilm0r/giggity#167]
In some of my previously created Pentabarf files I have very simple start and end time. For example for "Bibliothekartag 2020" which is also in the official menu of giggity I simply choose
```xml
    <start>2020-05-26</start>
    <end>2020-05-29</end>
```
That did work for giggity until recently. Now, I see some error about `DateTimeParserException`. I used the Pentabarf python library to create this, cf. https://github.com/UB-Mannheim/bibtag-scheduler/blob/master/schedule.py#L19-L20 and therefore I except this is possibly a newly introduce bug in giggity.

**Comment by zuphilip** [comment]
Ping @Wilm0r

**Comment by Wilm0r** [comment]
Sorry for the delay! Thanks for the Ping, this one did slip my mind.

So.. The joys of poorly standardised file formats... :-( Look at two other files:

* https://debconf20.debconf.org/schedule/pentabarf.xml
* https://programm.froscon.de/2020/schedule.xml

The <date/> field in those is a full date+time field with timezone info. Filling in just the date is redundant and confusing:

* It's a property to the containing <day/> tag already
* There's a start and an end time. What if the event runs past midnight? (Yes of course start time would be more logical, but still, IMHO it'd be poor naming.)

Having said that, of course Giggity shouldn't ~crash on this and just ignore wrongly formatted <date/> tags inside <event/>, so let me do that.

**Comment by Wilm0r** [comment]
I believe that this should now be back to the original behaviour when the <date/> tag is unusable.

**Comment by Wilm0r** [comment]
(Do let me know if you need a release due to this wonky formatting being used somewhere soon.)

**Comment by zuphilip** [comment]
Thank you for looking into this and hopefully fixing it.

I would appreciate a new release at some point with this fix also this is not time-critical for me. But it prevents me to look up again at my selected talks from some past conferences or have some example I can use as inspiration of new plans.
