### ISSUE TITLE
URL of website does not resolve anymore

### ISSUE THREAD

**Issue by zuphilip** [Wilm0r/giggity#183]
The mentioned URL of the website gaa.st/giggity does not resolve anymore. Maybe you want to give directly the URL https://wilmer.gaa.st/main.php/giggity.html or renew the redirect.

**Comment by Wilm0r** [comment]
Thanks for reporting this. It works again now, crappy Galera syncing seems to be less reliable than just running non-replicating SQL databases, which broke the redirector service...
