### ISSUE TITLE
MalformedURLException on Google-managed calendar for RIOT summit

### ISSUE THREAD

**Issue by chrysn** [Wilm0r/giggity#186]
The [RIOT summit](https://summit.riot-os.org/2021/) is coming up, and its calendar managed at https://calendar.google.com/calendar/ical/q8kbk375j3oh1ei3pt3s8g22hs%40group.calendar.google.com/public/basic.ics looks like it'd be suitable for use with giggity.

When attempting to load said URI (or its http version instead of https) by QR code, I get:

> Loading schedule data...
> Network I/O Problem: java.net.MalformedURLException: no protocol: https://calendar.google.com/calendar/ical/q8kbk375j3oh1ei3pt3s8g22hs%40group.calendar.google.com/public/basic.ics

Accessing the same resource per `curl` via termux (or via Firefox, which offers it for download) works, so it shouldn't be a network problem.

**Comment by Wilm0r** [comment]
Oh, there's no other bug for Scan QR not working, that's simply the evolution of Android. If an app wants to offer integrated QR scanning, it now has to be linked in (with camera permissions and all), and that'd be insane for niche functionality. If you do want to enter a schedule into Giggity using a QR you can use the ggt.gaa.st URL scheme (https://github.com/Wilm0r/giggity/blob/master/tools/ggt.sh for an example) and just use any QR scanner (Camera app usually has one) to open it.

Downside then of course is that it's Giggity-specific. The ggt.gaa.st name gets registered as a URL scheme on the phone, similar to how other apps do this. (Though of course I believe any compatible app could register that URL scheme instead.)
