### ISSUE TITLE
events seems to have different starttime in the gui

### ISSUE THREAD

**Issue by ka7** [Wilm0r/giggity#229]
**about:**
using 2.0.8 from fdroid

Run the url https://ggt.gaa.st/#url=https://www.linuxday.at/vortraege/2022/calendar.ics to create the QR, scanned, now showing in gigitty app on phone ( samsung, android 10)

In the .ics the TZ "berlin" is mentioned. 

screenshot from my phone: https://freeimage.host/i/PzlZFe

**problem:**

each event starts IRL at the full hour. ( 10:00 - 10:50, .. ) - in the table-display of giggity it looks like it starts something 10:15 -11:05. (when clicking into details, it shows correct time)

**only my problem** ?:

when checking the "fosdem 2019" i see both behaviors in the app ( some "off" the hour, some exact on the line .. its a bit harder here, as they had events starting at :35 ) )

**Comment by Wilm0r** [comment]
The colon of the clock, together with the dotted lines below them, align with the indicated time. I've always thought that was logical, and it's definitely how it's done in the old music festival block schedules that I was inspired by. Would that explain this?

**Comment by Wilm0r** [comment]
Timing out on this bug, but feel free to reopen if you still see this.
