### ISSUE TITLE
How to activate dark mode?

### ISSUE THREAD

**Issue by zuphilip** [Wilm0r/giggity#273]
I wonder how to activate the dark mode #42 for Giggity? The implementation of this should be done now and I have updated to version 2.1.

**Comment by Wilm0r** [comment]
Oh, it's not (for now?) possible to enable it within Giggity, it just picks up the darkness settings of your phone. I hope your phone is recent enough to support it? (And I think there should be a per-app forced dark mode on/off setting too?)

**Comment by Wilm0r** [comment]
Did you find a way BTW?

Not sure how hard it would be to add a setting for this within Giggity, so I hope that won't be needed..

**Comment by Wilm0r** [comment]
Android 10/API level 29 from 3-4 years ago seems to be the first version supporting it, which does seem old enough by now. https://medium.com/@phamduy.uit/android-10-to-be-ready-for-the-dark-mode-f8113dec9ea0

**Comment by zuphilip** [comment]
I have Android version 9 and that is apparently the problem. There is a "night mode" there, but no dark mode. No, I didn't find another way, but personally I can also use the other theme. On my tablet with a newer Android version, the dark mode works fine.
