### ISSUE TITLE
Instant crash when trying to open any conference program

### ISSUE THREAD

**Issue by Moini** [Wilm0r/giggity#302]
Hi @Wilm0r ! 

I've been wanting to take a screenshot to post about Giggity/Kielux in Social media, but unfortunately, Giggity crashes instantly when I try to open any conference program :-(

1.  Open App
2.  Have settings set to start with anything but 'Programmübersicht' (program overview?)
3. Tap on any conference title
4. Bam... 

If I choose 'Program overview' in the settings, it does show something, but only for a single room - in the case of Kielux, only Room 114.

If I then click on 
* 'Now and soon': Bam
* 'Timetable' (hope I backtranslated them correctly): returns to start page with overview about conferences
* 'Search': Bam
* My Schedule: Bam
* ...

**Comment by Moini** [comment]
(In case it's limited to specific Android versions: Mine is oooooold. LineageOS based on Android 9. Afraid to update, in case it bricks...)

**Comment by Wilm0r** [comment]
Uhoh :-( Happen to have and logcat so that you can generate logs/backtrace? Or maybe your device submitted one already. I'm away from my laptop for a few days so can't check :-(

**Comment by Moini** [comment]
@Wilm0r I have an old version of adb installed (because that can still do backups), but it might work to collect a backtrace. 

I've never used it in that way, though. Do you happen to know the command I'd need to use to get just the relevant info out of my phone? (hopefully that hasn't changed in the last 4 years or so...)

I don't think my device submits anything like that, using the F-Droid version and it not asking me to allow it to send something...

**Comment by Wilm0r** [comment]
`adb logcat` shouldn't have changed much at least! I think you could figure out the PID of your Giggity process and grep for that, but otherwise it's going to be spammy and include other processes on your phone.

I've checked the crash dumps submitted via Play Store and I see nothing (yet) at least. And without a stacktrace there is not much I can do, despite the thorough steps to reproduce above :(

Looks like at least Android 9 == API 26 which is exactly Giggity's current `minSdkVersion` .pfew..

**Comment by Moini** [comment]
@Wilm0r  Thanks! 

I've done an 'adb logcat > /tmp/log.txt' while triggering the crash, and grepped for 'giggity' in the resulting file.

This is the result:

[giggity.log.txt](https://github.com/Wilm0r/giggity/files/12505994/giggity.log.txt)

In case it's important: The device is offline, not connected to the web.

**Comment by Wilm0r** [comment]
Android logs are a hot mess, grepping for `giggity` isn't super helpful. :( Can you capture a full log and search for anything that looks like a relevant stacktrace and share that in full?

**Comment by Wilm0r** [comment]
> In case it's important: The device is offline, not connected to the web.

Ah yes that can be relevant, we'll see. Does the device "know" it's offline or is it getting blackholed?

**Comment by Moini** [comment]
I think this one looks relevant (included a couple additional lines as I cannot tell where exactly it starts):

```
09-03 14:07:38.610   629   629 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
09-03 14:07:38.610   629   629 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
09-03 14:07:38.836   797   820 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
09-03 14:07:38.909 17335 17335 D AndroidRuntime: Shutting down VM
09-03 14:07:38.910 17335 17335 E AndroidRuntime: FATAL EXCEPTION: main
09-03 14:07:38.910 17335 17335 E AndroidRuntime: Process: net.gaast.giggity, PID: 17335
09-03 14:07:38.910 17335 17335 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/text/MeasuredText$Builder;
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at net.gaast.giggity.ScheduleListView.<init>(ScheduleListView.java:52)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at net.gaast.giggity.NowNext.<init>(NowNext.java:1)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at net.gaast.giggity.ScheduleViewActivity.redrawSchedule(ScheduleViewActivity.java:130)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at net.gaast.giggity.ScheduleViewActivity.onOptionsItemSelectedInt(ScheduleViewActivity.java:117)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at net.gaast.giggity.ScheduleViewActivity$2.onClick(ScheduleViewActivity.java:9)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.text.MeasuredText$Builder" on path: DexPathList[[zip file "/data/app/net.gaast.giggity-K99VGQToG18w8awBACX7kA==/base.apk"],nativeLibraryDirectories=[/data/app/net.gaast.giggity-K99VGQToG18w8awBACX7kA==/lib/arm64, /system/lib64]]
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-03 14:07:38.910 17335 17335 E AndroidRuntime: 	... 16 more
09-03 14:07:38.914  1338  2022 W ActivityManager:   Force finishing activity net.gaast.giggity/.ScheduleViewActivity
09-03 14:07:38.919 17335 17335 I Process : Sending signal. PID: 17335 SIG: 9
09-03 14:07:38.935  1338 17370 W DropBoxManagerService: Dropping: data_app_crash (1830 > 0 bytes)
09-03 14:07:38.950  1338  1762 E InputDispatcher: channel 'fca2e6a net.gaast.giggity/net.gaast.giggity.ScheduleViewActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-03 14:07:38.958  1338  1762 W InputDispatcher: channel '9f399ae net.gaast.giggity/net.gaast.giggity.ChooserActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-03 14:07:38.958  1338  1762 E InputDispatcher: channel '9f399ae net.gaast.giggity/net.gaast.giggity.ChooserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-03 14:07:38.959  1338  2022 I WindowManager: WIN DEATH: Window{fca2e6a u0 net.gaast.giggity/net.gaast.giggity.ScheduleViewActivity}
09-03 14:07:38.959  1338  2022 W InputDispatcher: Attempted to unregister already unregistered input channel 'fca2e6a net.gaast.giggity/net.gaast.giggity.ScheduleViewActivity (server)'
09-03 14:07:38.959  1338  1489 W libprocessgroup: kill(-17335, 9) failed: No such process
09-03 14:07:38.959  1338  1489 I libprocessgroup: Successfully killed process cgroup uid 10117 pid 17335 in 0ms
09-03 14:07:38.960  1338  5311 I ActivityManager: Process net.gaast.giggity (pid 17335) has died: fore TOP 
09-03 14:07:38.960   684   684 I Zygote  : Process 17335 exited due to signal (9)
```

The device is in flight mode, and WiFi is turned off. It *should* be able to know that, I believe. I am using a local VPN to be able to block internet access for some apps (NetGuard). Giggity has access, though.

It also crashes when WiFi is on... sorry for the wrong trail.

**Comment by Wilm0r** [comment]
Wow, what the hell...

https://developer.android.com/reference/android/graphics/text/MeasuredText

Added in [API level 29](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)

That's 3 beyond where you are. And for whatever the reason may be, Android Studio didn't warn me about using incompatible APIs. 🙄 Let's see whether to fix this with appcompat trash or by just hardcoding some layout element sizes again ...

**Comment by Moini** [comment]
Yeah... after Kielux, I really need to risk the update... requires resetting to the original ROM with some Motorola program, and using Windows, then the actual install of Lineage 20. Scary stuff to me :) Thank you for looking into this and assuring compatibility with older versions.

**Comment by Wilm0r** [comment]
Yeah, old versions at least up to some point *are* important. I'm surprised it took this long for someone (you) to find this bug actually, it's pretty serious! :(

Are you running Giggity from the Play Store or from F-Droid? I can't really safely do a release from HEAD right now but could maybe just send you a build from right before the `MeasuredText` change..

**Comment by Wilm0r** [comment]
2.1.1 is now available on the dev track. https://play.google.com/apps/testing/net.gaast.giggity to sign up.

**Comment by Wilm0r** [comment]
F-Droid seems to have picked up 2.1.2 in source but not on https://f-droid.org/en/packages/net.gaast.giggity/ yet :(

I may figure out a wrapped up 2.2 this week(end).

Thanks for the report! Looks like a few people ran into it but not many (or many did but have stacktrace submission to Google disabled)... so I guess most devices are rather up to date.
