### ISSUE TITLE
Mitigate unreadable schedules  (difficult to find a good zoom / pinch)

### ISSUE THREAD

**Issue by valerio-bozzolan** [Wilm0r/giggity#370]
Premise: I love the Giggity app. Thanks for your work :rainbow:

-----

A frequent negative feedback I receive after promoting Giggity, is that it's relatively easy to shoot in your foot and cause an unreadable layout during normal user interaction in the BlockSchedule activity.

For example, it's relatively super-easy to cause this broken layout where the cell width is so low that not even a single word stays in a single line. You cannot even read the times in the headers. Moreover, if cell widths become smaller, texts GROWS :D this may not help in general readability:

> ![Giggity layout with very small cell height](https://github.com/user-attachments/assets/e0608c09-6b55-4107-9351-2062733fc201)
> https://wikimania.eventyay.com/2024/

## Workaround

The user can just use their powerful fingers to find a better zoom with the usual pinch gesture.

Anyway, it's not so obvious: the preview you see during zoom-pinch reflects the future size but it does not really reflect the future font-size, so it's a kind of "try catch" approach, to continue to try different pinches to obtain a readable layout.

Moreover, the user can open their app preferences and set the "small" font size preference.

## Actionable Things

Probably we can mitigate the situation by "just" increasing our width/height minimum thresholds.

I think we already have something in place in `onResizeEvent()`:

https://github.com/Wilm0r/giggity/blob/8eb5c049e2928fb77d5a4b593df319bff74c03d8/app/src/main/java/net/gaast/giggity/BlockSchedule.java#L265

So probably we could increase that `60` to something bigger:

```
HourWidth = Math.max(60, ...); 
```

For example, increasing that `60` to a greater/better value.

That feature was introduced in 2013 (12+ years ago) and probably never touched again (https://github.com/Wilm0r/giggity/commit/108019477cebb3d13c277468d3e24c05984f6e27).

Additionally, we should prevent the default font size from being in proportion of the "cell density" but it should probably (also?) consider the "cell width". The relevant code seems here:

https://github.com/Wilm0r/giggity/blob/8eb5c049e2928fb77d5a4b593df319bff74c03d8/app/src/main/java/net/gaast/giggity/BlockSchedule.java#L117 

Also the above feature was introduced 8+ years ago and never touched again (https://github.com/Wilm0r/giggity/commit/f852dc546dafee8b4898229c054ae79ef1657ca7).

Thanks for any feedback or any patch :) Long life to Giggity.

**Comment by Wilm0r** [comment]
Wow very nicely written bug report, my apologies for such a late response. :(

Indeed I can easily reproduce this and as is typical, I the author know how to fix it and just pinch myself back to safety. But you're right, there should just be restrictions on what width/height ratio it allows.

For sure that code is VERY old indeed, not my favourite part of the code base to work on... (At times I've considered rewriting it without `AbsoluteLayout` because you're not supposed to use it, but then hey it works fine, bugs like this one aside?)

**Comment by valerio-bozzolan** [comment]
Yeah "don't rewrite just patch 🎵 " 👍

**Comment by Wilm0r** [comment]
95f6bb2 should help I hope. Pretty modest change and one can certainly still produce weird results, but I think it'll definitely take more intent than accident now. :)

**Comment by valerio-bozzolan** [comment]
I will test this at next FOSDEM from F-Droid :smile: thanks again, seems promising

**Comment by valerio-bozzolan** [comment]
Maybe we need to git tag, and update version code and number to test at FOSDEM :3 :3

**Comment by Wilm0r** [comment]
Heh, yep, done! The tag should ensure an F-Droid release hopefully in time, and well we'll see how long Play Store reviews take this time. Coincidentally the last release was exactly a year ago and not much has changed...

**Comment by Wilm0r** [comment]
Play Store updated now BTW. No idea where you're installing it from but if you think this is still not great (I should probably adjust the minimum for example) just let me know! Trying to find a balance between not restricting some people's odd choices and not having them accidentally do something weird with one clumsy swipe.

**Comment by valerio-bozzolan** [comment]
> No idea where you're installing it from

(I'm an F-Droid lover :3 no Google Apps in my droid.)

Thanks! I will share feedback as soon as possible (→ maybe 4 days. F-Droid is slow in processing)

**Comment by Wilm0r** [comment]
Did it help?

**Comment by valerio-bozzolan** [comment]
Yup, a lot better thanks!

**Comment by valerio-bozzolan** [comment]
For historical reasons, I attach the nice situation after the change.

I tried to replicate the "worst" situation, and any zoom pinch resulted in a much better situation 😻 😻 Thanks again!

<img width="1224" height="2700" alt="Image" src="https://github.com/user-attachments/assets/0ef633df-3fbd-4c42-b84f-40b171eb4055" />
