### ISSUE TITLE
build new version ?

### ISSUE THREAD

**Issue by ka7** [Wilm0r/giggity#40]
I see now at least 2 events in beginning of Dec... would be nice if you could push **soon** a new version (which just includes the latest events).
( I think it would at least appear automatic in f-droid, not sure about g-play )

thanks for considering.

Also, **long-therm** i would suggest to split the "app" and the "data" into 2 repos.
- the data (res/raw/menu.json) could then be refresh-loaded by the app separately (maybe even from the master repo raw.github.org :) )
- also the data could be included (there some gradle receipts) to be included if build a new version

for the data-repo, there could run some custom .travis checks for to prove pull-requests. (are the urls accessible, is the .ics file a valid one, check the format (json-schema-validation), ... )

**Comment by Wilm0r** [comment]
Hrm, menu.json is loaded from a webserver so already released separately from Giggity itself, exactly for reasons like this.. It's been like that from the start, I never wanted to have to do releases just for getting a new event into the menu.

The copy on https://wilmer.gaa.st/deoxide/menu.json does appear to be in sync with the one in this repo. What are you seeing out of sync exactly?

**Comment by ka7** [comment]
ah... i missed that one - that explains a lot.
I was thinking this is included at compile time, as it´s in same repo...
nevermind - I'm happy now. :)
