### ISSUE TITLE
Fehler beim Laden "34c3": Network I/O problem: java.io.IOException: Download error

### ISSUE THREAD

**Issue by Wikinaut** [Wilm0r/giggity#41]
When scanning the QR code of https://events.ccc.de/congress/2017/Fahrplan/qrcode.html , I got "Fehler beim Laden".

**Comment by schumar** [comment]
I managed to add the schedule by manually entering the URL https://events.ccc.de/congress/2017/Fahrplan/schedule.xml

The QR code only says `//events.ccc.de/congress/2017/Fahrplan/`, so I'm not sure if this is actually an issue with Giggity

**Comment by Wilm0r** [comment]
Huh, that's pretty weird yeah :-( Guess the best fix is to get it into menu.json IOW merge https://github.com/Wilm0r/giggity/pull/43 so people don't have to bother with any QR at all.

**Comment by Wilm0r** [comment]
Ha, even here on https://fahrplan.events.ccc.de/congress/2017/Fahrplan/schedule.xml I see this:

<base_url>//fahrplan.events.ccc.de/congress/2017/Fahrplan/</base_url>

I .... guess this is a valid URL in some places, it kinda is a valid relative URL in browsers/HTML AFAIK. But I'm pretty sure a statement liket his one should have absolute URLs...

Anyway, not a Giggity bug. "Fixing" this through menu.json now. Thanks for the report anyway :-)

**Comment by Wikinaut** [comment]
![qr](https://user-images.githubusercontent.com/1151915/34116009-7737d492-e417-11e7-8a5d-1de4524aac79.png)

generated in my browser add-on.

**Comment by Wikinaut** [comment]
@Wilm0r Thank you all. I informed the CCC team to fix their QR code!

**Comment by Wikinaut** [comment]
@erdgeist told me, I should notify frab. Done with https://github.com/frab/frab/issues/386

**Comment by manno** [comment]
This was put there intentionally, but I don't know why. Changed it to a full URL with protocol. frab should [validate this in the future, maybe](https://github.com/frab/frab/issues/387).

**Comment by mmuman** [comment]
The "//..." scheme is on purpose I think, it's a [protocol-relative URL](https://www.paulirish.com/2010/the-protocol-relative-url/), that is, it assumes to be the same protocol as the referrer. This is to avoid mixed content in web pages. We should probably prepend https: there.

**Comment by Wilm0r** [comment]
Yeah I know, see my comment above https://github.com/Wilm0r/giggity/issues/41#issuecomment-352439195 - I think it's done in some contests where IMHO relative URLs shouldn't be valid, including the QR code for example (no context from where to support a relative URL, right?).

**Comment by mmuman** [comment]
Indeed, there's no referrer there.
