### ISSUE TITLE
background update

### ISSUE THREAD

**Issue by chrysn** [Wilm0r/giggity#54]
On events with volatile schedules, I run with "Always reload schedules", but that takes some time in the morning, and makes the cached schedule inaccessible if network errors occur.

Could the schedule update process be moved into the background (open, it shows the cached schedule right away and refreshes when updates are parsed), and made to keep using the last good version in presence of network errors?

Thanks for this great app!

**Comment by Wilm0r** [comment]
Basic implementation finally in https://github.com/Wilm0r/giggity/commit/b5ffc48634c08d1fbe13285bbee8cf236a940757

Still needs lots of polishing but I mostly like the result.

**Comment by Wilm0r** [comment]
#19 ended up with more discussion so moving to that one.
