### ISSUE TITLE
wishlist: floor plans

### ISSUE THREAD

**Issue by chrysn** [Wilm0r/giggity#55]
Comparing giggity to all those conference apps I see on colleagues' phones, the only benefit they give is having a floor plan accessible.

Could we come up with a way in which organizers can annotate the rooms in their ICS files with floor plans, and if it is only a link that opens in the browser?

Suggestion: `LOCATION:Balmoral` could be annotated as `LOCATION;ALTREP="https://datatracker.ietf.org/meeting/101/floor-plan?room=balmoral:Balmoral"`.

**Comment by Wilm0r** [comment]
Oh hah, you've managed to get the IETF101 schedule into Giggity? Glad that's working. :-) (I'm sitting only 3km away or so and considered going...)

Anyway, luckily we do already have this, though it only works through menu.json metadata. Try opening the FOSDEM schedule for example. If you have a PNG/PDF we could make this happen for IETF101 as well.

IMHO Giggity's even better (unless other apps copied this by now :-P) in that you can have coordinate data in menu.json as well which will add maps/nav intent links/buttons to the UI in a few places.

**Comment by Wilm0r** [comment]
Hrm, so there are in fact apps that have a schematic map *and* will try to guess where you are and render this?

Giggity has A) the option to off-line show PDF/PNG maps but without localisation or B) ability to trigger map location intents to be handled by Google Maps or whatever you prefer.

Doing something clever with georeferenced PNGs does seem like a lot of work, don't know how many would be interested in that..

**Comment by chrysn** [comment]
> Hrm, so there are in fact apps that have a schematic map *and* will
> try to guess where you are and render this?

I don't know, I think they are just having static images.

> Doing something clever with georeferenced PNGs does seem like a lot of
> work, don't know how many would be interested in that..

No, and while I'd quite like that I know it's not feasible, if only
because it's not often used for that.

> Giggity has A) the option to off-line show PDF/PNG maps but without
> localisation or B) ability to trigger map location intents to be
> handled by Google Maps or whatever you prefer.

IMO it would be good enough to use that -- but not only per conference
byt per room, pointing at a web page that renders something or to a
static image of a floor plan with a red dot on it.

**Comment by Wilm0r** [comment]
Oh there's also c3nav integration now. I'd say this is all good enough now? (Though it's a shame that web-c3nav still doesn't support the "show on the map where I am now" button and the app version AFAIK is still CCC-only?)
