### ISSUE TITLE
Easiest way to create event calendar?

### ISSUE THREAD

**Issue by frontierpsycho** [Wilm0r/giggity#57]
I want to try to create an event calendar for giggity for a boardgame con I'm going to attend. What's the easiest way to create any of the formats that giggity reads? I mean the file whose url will go into the top level `url` field of the JSON file for the event. 

I'm looking for a broad description in steps or pointers. Assume I know programming and am prepared to do a little work for this.

**Comment by MHohenberg** [comment]
Giggity is just a viewer for the Pentabarf/FRAB family of event management systems. Please look here: https://github.com/frab/frab

Other than that, just take a random frab and take a look at the output: https://entropia.de/GPN18:Fahrplan

**Comment by frontierpsycho** [comment]
Well, I did use frab after all, the event already passed. Thanks!
