### ISSUE TITLE
If the conference is ongoing, jump to the current date

### ISSUE THREAD

**Issue by MHohenberg** [Wilm0r/giggity#62]
If you select a conference that is currently in progress, giggity seems to always jump to the first day of the conference. 

Preferred behavior would be to jump to the current day.

**Comment by Wilm0r** [comment]
It should remember the day you were looking at by the way, so you should really have this problem only once a day at most. Was that buggy (forgetful) for you?

**Comment by Wilm0r** [comment]
Let's try it that way.
