### ISSUE TITLE
Port to SailfishOS

### ISSUE THREAD

**Issue by Astaoth** [Wilm0r/giggity#68]
Hey,
This is a very usefull app ! Do you think it will be possible to make a version for Sailfish OS ? :)
Cheers !

**Comment by Astaoth** [comment]
Sailfish OS can run Android apps (which don't require too much ressources) only on smartphones which are officially supported, but there are many other smartphones on which you can install SailfishOS. In addition, the Android VM eats many ressources, there are no good performances, is not updated on all the devices (for example, on Jolla 1 there is no more update). So, it's like running Windows in Virtualbox or trying to play with Wine on a laptop, but only on some of them.
Now, for answering to your question, yes it runs, but with a higher CPU and RAM consumption than on Android (because of the VM).

**Comment by Wilm0r** [comment]
Sorry, but porting to an entirely new OS is really a *lot* of work and I won't be doing it as part of Giggity.

I don't know whether Sailfish OS takes Java, but if so, anyone should feel free to borrow bits of Giggity code (like the schedule parser).

Closing this bug here though.
