### ISSUE TITLE
Add F-Droid badge in README.md

### ISSUE THREAD

**Issue by PanderMusubi** [Wilm0r/giggity#9]
Please, add the F-Droid bade in the README.md by adding the following lines:

    <a href="https://f-droid.org/app/net.gaast.giggity">
        <img src="https://f-droid.org/badge/get-it-on.png"
             alt="Get it on F-Droid" height="80">
    </a>

Possibly, also add this to https://wilmer.gaa.st/main.php/giggity.html

**Comment by Wilm0r** [comment]
Might as well. Done. Did make it a little smaller. (height=64)
